# Generated by Django 4.0 on 2024-11-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.TextField(max_length=100)),
                ('Phone_Number', models.TextField(max_length=10, null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Message', models.TextField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Last_login',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Login_Time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'last_login',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_name', models.TextField(max_length=100)),
                ('Image', models.FileField(null=True, upload_to='images/')),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Address', models.TextField(max_length=200, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Phone_Number', models.TextField(max_length=10, null=True)),
                ('Password', models.TextField(max_length=15, null=True)),
                ('Date_Time', models.DateTimeField(auto_now=True, null=True)),
                ('User_Status', models.TextField(default='pending', max_length=50, null=True)),
                ('Last_Login_Time', models.TimeField(null=True)),
                ('Last_Login_Date', models.DateField(auto_now_add=True, null=True)),
                ('No_Of_Times_Login', models.IntegerField(default=0, null=True)),
                ('Message', models.TextField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
