# Generated by Django 4.2 on 2026-02-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LR',
            new_name='LiteFDNet',
        ),
        migrations.RenameModel(
            old_name='EnsembleModel',
            new_name='PlainNet',
        ),
        migrations.RenameModel(
            old_name='XGB',
            new_name='RF',
        ),
        migrations.AlterModelTable(
            name='litefdnet',
            table='LiteFDNet',
        ),
        migrations.AlterModelTable(
            name='plainnet',
            table='PlainNet',
        ),
        migrations.AlterModelTable(
            name='rf',
            table='RF',
        ),
    ]
