# Generated by Django 4.0 on 2024-11-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('Data_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
    ]
